# Generated by Django 4.2.2 on 2023-08-07 06:07

from django.db import migrations, models

import umap.models


class Migration(migrations.Migration):
    dependencies = [
        ("umap", "0010_alter_map_edit_status_alter_map_share_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="edit_status",
            field=models.SmallIntegerField(
                choices=[(1, "Everyone"), (2, "Editors only"), (3, "Owner only")],
                default=umap.models.get_default_edit_status,
                verbose_name="edit status",
            ),
        ),
        migrations.AlterField(
            model_name="map",
            name="share_status",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Everyone (public)"),
                    (2, "Anyone with link"),
                    (3, "Editors only"),
                    (9, "Blocked"),
                ],
                default=umap.models.get_default_share_status,
                verbose_name="share status",
            ),
        ),
    ]
