# Generated by Django 4.2.2 on 2023-09-07 06:27

from django.db import migrations, models
import umap.models


class Migration(migrations.Migration):
    dependencies = [
        ("umap", "0012_datalayer_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="datalayer",
            name="edit_status",
            field=models.SmallIntegerField(
                choices=[(1, "Everyone"), (2, "Editors only"), (3, "Owner only")],
                default=umap.models.get_default_edit_status,
                verbose_name="edit status",
            ),
        ),
    ]
