# Generated by Django 4.2.2 on 2023-09-12 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("umap", "0013_datalayer_edit_status"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE umap_datalayer SET edit_status=("
            "SELECT edit_status FROM umap_map WHERE umap_map.id=umap_datalayer.map_id);"
        )
    ]
