# Generated by Django 5.0.8 on 2024-08-21 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("umap", "0021_remove_map_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datalayer",
            old_name="settings",
            new_name="metadata",
        ),
        migrations.RenameField(
            model_name="datalayer",
            old_name="geojson",
            new_name="data",
        ),
        migrations.RenameField(
            model_name="map",
            old_name="settings",
            new_name="metadata",
        ),
        migrations.RunSQL("UPDATE umap_map SET metadata=metadata->'properties'"),
    ]
