# Generated by Django 5.2.8 on 2026-01-13 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("umap", "0028_map_is_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="datalayer",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="umap.datalayer",
            ),
        ),
    ]
