# Generated by Django 5.2.1 on 2025-05-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umap', '0028_datalayer_editors_alter_datalayer_edit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalayer',
            name='edit_status',
            field=models.SmallIntegerField(choices=[(0, 'Inherit'), (1, 'Everyone'), (2, 'Editors and team only'), (4, 'Selected Users, Teams and Owner'), (3, 'Owner only')], default=0, verbose_name='edit status'),
        ),
    ]
