# Generated by Django 5.2.1 on 2025-05-17 21:53

import umap.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umap', '0029_alter_datalayer_edit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='team',
        ),
        migrations.AddField(
            model_name='datalayer',
            name='teams',
            field=models.ManyToManyField(blank=True, to='umap.team', verbose_name='teams'),
        ),
        migrations.AddField(
            model_name='map',
            name='teams',
            field=models.ManyToManyField(blank=True, to='umap.team', verbose_name='teams'),
        ),
        migrations.AlterField(
            model_name='datalayer',
            name='edit_status',
            field=models.SmallIntegerField(choices=[(0, 'Inherit'), (1, 'Everyone'), (2, 'Editors and teams only'), (4, 'Selected Users, Teams and Owner'), (3, 'Owner only')], default=0, verbose_name='edit status'),
        ),
        migrations.AlterField(
            model_name='map',
            name='edit_status',
            field=models.SmallIntegerField(choices=[(1, 'Everyone'), (2, 'Editors and teams only'), (3, 'Owner only')], default=umap.models.get_default_edit_status, verbose_name='edit status'),
        ),
        migrations.AlterField(
            model_name='map',
            name='share_status',
            field=models.SmallIntegerField(choices=[(0, 'Draft (private)'), (1, 'Everyone (public)'), (2, 'Anyone with link'), (3, 'Editors and teams only'), (9, 'Blocked'), (99, 'Deleted')], default=umap.models.get_default_share_status, verbose_name='share status'),
        ),
    ]
