# Generated by Django 5.1.4 on 2024-12-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Peer",
            fields=[
                (
                    "uuid",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("room_id", models.CharField(max_length=200)),
            ],
        ),
    ]
