name: Test & Docs

on:
  push:
    branches: [master]
  pull_request:
    path:
      - umap/*
      - pyproject.toml

jobs:
  tests:
    if: github.event.pull_request.draft == false
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:14-3.4
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12', '3.14']
        database: [postgresql]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libgdal-dev
          make ci
          npm install mocha
      - name: run tests
        run: make test
        env:
          DJANGO_SETTINGS_MODULE: 'umap.tests.settings'
          UMAP_SETTINGS: 'umap/tests/settings.py'
          PLAYWRIGHT_TIMEOUT: '20000'
          REDIS_HOST: localhost
          REDIS_PORT: 6379
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: |
          make ci
          npm install eslint

      - name: Run Lint
        run: make lint

      - name: Run Docs
        run: make docs
